[package]
name = "bruhlang"
version = "0.1.0"
authors = ["Gauns <43172308+Gauns@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "0.1.0"
crossterm = "0.17.5"
rodio = "0.11.0"